👷 CI: integration test create_service Lambda
🏔️ 🔊 TERRAFORM: configure cluster name, service name and Lambda
function name outputs

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -393,7 +393,7 @@ jobs:
         if: ${{ steps.configure-aws.outcome == 'success' }}
         run: ./switch_env.sh stage
 
-      - name: Terraform plan with check for changes
+      - name: Terraform plan with check for changescompliant
         id: terraform-plan
         working-directory: infra
         if: ${{ steps.configure-aws.outcome == 'success' }}
@@ -402,8 +402,7 @@ jobs:
           terraform plan \
             -detailed-exitcode \
             -out=tfplan \
-            -var-file="envs/stage/terraform.tfvars" \
-            -var="BUDIBASE_TASK_COUNT=1"
+            -var-file="envs/stage/terraform.tfvars"
           EXIT_CODE="$?"
           set -e
 
@@ -424,11 +423,51 @@ jobs:
         run: |
           terraform apply tfplan
             echo "lb_url=\"$(terraform output -raw lb_url)\"" >> $GITHUB_OUTPUT
+            echo "cluster_name=\"$(terraform output -raw budibase_ecs_cluster_name)\"" \
+              >> $GITHUB_OUTPUT
+            echo "create_service_function_name=\"$(terraform output -raw lambda_create_service_name)\"" \
+              >> $GITHUB_OUTPUT
+            echo "destroy_service_function_name=\"$(terraform output -raw lambda_destroy_service_name)\"" \
+              >> $GITHUB_OUTPUT
 
       - name: Clean up Terraform plan file
         working-directory: infra
         if: ${{ steps.terraform-plan.outputs.runapply == 'true' }}
         run: rm -f tfplan
+
+      - name: "Lambda integration test: create-instance-lambda"
+        if: ${{ steps.terraform-plan.outputs.runapply == 'true' }}
+        run: |
+          # Confirm Terraform applied with BUDIBASE_TASK_COUNT=0
+          DESIRED_COUNT="$(aws ecs describe_services \
+            --cluster "${{ steps.terraform-apply.outputs.cluster_name }}" \
+            --services "${{ steps.terraform-apply.outputs.service_name }}" \
+            | jq -r '.services[0].desiredCount')"
+          if [ "$DESIRED_COUNT" != 0 ]; then
+            echo "Non-compliant integration test environment: initial" \
+              "ECS desiredCount is $DESIRED_COUNT, not 0."
+            exit 1;
+          else
+            "Integration test environment meets expectations. ECS desiredCount is 0."
+          fi
+
+          # Invoke the Lambda function
+          FUNC_NAME="${{ steps.terraform-apply.outputs.create_service_function_name }}"
+          echo "Invoking Lambda function $FUNC_NAME ..."
+          aws lambda invoke --function-name "$FUNC_NAME" lambda.out
+
+          # Confirm ECS desiredCount is now 1
+          DESIRED_COUNT="$(aws ecs describe_services \
+            --cluster "${{ steps.terraform-apply.outputs.cluster_name }}" \
+            --services "${{ steps.terraform-apply.outputs.service_name }}" \
+            | jq -r '.services[0].desiredCount')"
+          if [ "$DESIRED_COUNT" != 1 ]; then
+            echo "Integration test failed: expected desiredCount 1 after" \
+              "$FUNC_NAME run, got $DESIRED_COUNT."
+            exit 1;
+          else
+            "Integration test successful: after $FUNCT_NAME run, desiredCount is 1."
+          fi
 
       - name: Post-apply validation
         if: ${{ steps.terraform-plan.outputs.runapply == 'true' }}
