👷 CI: fetch SSM fallback manifest ID if no manifest found for base SHA
👷 CI: output elder SHA of SSM manifest ID and merge base as comparison base for rest of workflow

🐛 CI: remove conditional skipping of list-changes and generate-shas

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,9 +22,9 @@ jobs:
       lambda_create_instance_changed: ${{ steps.list-changes.outputs.lambda_create_instance_changed }}
       lambda_destroy_instance_changed: ${{ steps.list-changes.outputs.lambda_destroy_instance_changed }}
 
-      short_sha_branch_base: ${{ steps.short-shas.outputs.short_sha_branch_base }}
-      short_sha_branch_head: ${{ steps.short-shas.outputs.short_sha_branch_head }}
-      short_sha_merge: ${{ steps.short-shas.outputs.short_sha_merge }}
+      short_sha_base: ${{ steps.manifest-and-shas.outputs.short_sha_base }}
+      short_sha_branch_head: ${{ steps.manifest-and-shas.outputs.short_sha_branch_head }}
+      short_sha_merge: ${{ steps.manifest-and-shas.outputs.short_sha_merge }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v6
@@ -32,13 +32,90 @@ jobs:
           # Ensure unshallow fetch to allow for merge-base checks
           fetch-depth: 0 
 
+      - name: Configure AWS credentials
+        id: configure-aws
+        uses: aws-actions/configure-aws-credentials@v6.0.0
+        with:
+          aws-access-key-id:
+            ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key:
+            ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region:
+            ${{ vars.AWS_REGION }}
+
+      - name: Fetch base manifest and generate SHAs
+        id: manifest-and-shas
+        run: |
+          # Generate short SHAs
+          SHORT_SHA_BASE="$(git rev-parse --short "${{ github.event.pull_request.base.sha }}")"
+          SHORT_SHA_BRANCH_HEAD="$(git rev-parse --short "${{ github.event.pull_request.head.sha }}")"
+          SHORT_SHA_MERGE="$(git rev-parse --short "${{ github.sha }}")"
+
+          # Print SHAs to log for reference
+          printf "Branch base SHA: %s\nBranch head SHA: %s\nCandidate/actual merge SHA: %s\n" \
+            "$SHORT_SHA_BASE" "$SHORT_SHA_BRANCH_HEAD" "$SHORT_SHA_MERGE"
+
+          # Try to fetch base manifest
+          echo "Fetching manifest with id $SHORT_SHA_BASE from S3..."
+          set +e
+          aws s3 cp \
+            --region "${{ vars.AWS_REGION }}" \
+            "s3://${{ vars.MANIFEST_BUCKET }}/${SHORT_SHA_BASE}.json" \
+            manifest.json
+          EXIT_CODE="$?"
+          set -e
+
+          if [ $EXIT_CODE -eq 1 ]; then
+            echo "Manifest not found. Falling back on SSM value..."
+            SSM_MANIFEST_ID="$(
+              aws ssm get-parameter \
+                --region "${{ vars.AWS_REGION }}" \
+                --name "${{ vars.SSM_PARAM_NAME_MANIFEST_ID }}" \
+                | jq -r '.Parameter.Value'
+            )"
+            echo "Fetching manifest with id $SSM_MANIFEST_ID from S3..."
+            aws s3 cp \
+              --region "${{ vars.AWS_REGION }}" \
+              "s3://${{ vars.MANIFEST_BUCKET }}/${SSM_MANIFEST_ID}.json" \
+              manifest.json
+            echo "Manifest fetched successfully. Checks will continue with amended" \
+              "base sha $SHORT_SHA_BASE." 
+
+            echo "Manifest fetched successfully."
+
+            # Update our working base SHA to whichever is older
+            if git merge-base --is-ancestor "$SSM_MANIFEST_ID" "$SHORT_SHA_BASE"; then
+              echo "SSM's $SSM_MANIFEST_ID is an ancestor of branch base $SHORT_SHA_BASE." \
+                "Checks will continue with amended base SHA $SSM_MANIFEST_ID."
+              SHORT_SHA_BASE="$SSM_MANIFEST_ID"
+            else
+              echo "Branch base $SHORT_SHA_BASE is an ancestor of SSM's $SSM_MANIFEST_ID." \
+                "Checks will continue with existing base SHA."
+          else
+            echo "Manifest fetched successfully."
+          fi
+
+          # Output final SHAs for use throughout workflow
+          echo "short_sha_base=$SHORT_SHA_BASE" >> $GITHUB_OUTPUT
+          echo "short_sha_branch_head=$SHORT_SHA_BRANCH_HEAD" >> $GITHUB_OUTPUT
+          echo "short_sha_merge=$SHORT_SHA_MERGE" >> $GITHUB_OUTPUT
+
+      - name: Upload manifest artefact
+        uses: actions/upload-artifact@v4
+        with:
+          name: base-manifest-${{ github.run_id }}
+          path: manifest.json
+          if-no-files-found: error
+          retention-days: 1
+
       - name: Check for intervening merges
         id: check-merges
         # Check for other merges only if this is a post-merge run
         if: ${{ github.event.pull_request.merged == true }}
         run: |
+          SHORT_SHA_BASE="${{ steps.manifest-and-shas.outputs.short_sha_base }}"
           TOTAL_REVS=$(git rev-list \
-            --count ${{ github.event.pull_request.base.sha }}..${{ github.sha }})
+            --count ${{ steps.manifest-and-shas.outputs. }}..${{ github.sha }})
           BRANCH_REVS=$(git rev-list \
             --count ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
 
@@ -106,54 +183,7 @@ jobs:
             >> $GITHUB_OUTPUT
           echo "lambda_destroy_instance_changed=$LAMBDA_DESTROY_INSTANCE_CHANGED" \
             >> $GITHUB_OUTPUT
-      
-      - name: Generate short SHAs
-        id: short-shas
-        if: ${{ steps.list-changes.outcome == 'success' }}
-        run: |
-          SHORT_SHA_BRANCH_BASE="$(git rev-parse --short "${{ github.event.pull_request.base.sha }}")"
-          SHORT_SHA_BRANCH_HEAD="$(git rev-parse --short "${{ github.event.pull_request.head.sha }}")"
-          SHORT_SHA_MERGE="$(git rev-parse --short "${{ github.sha }}")"
 
-          # Print SHAs to log for reference
-          printf "Branch base SHA: %s\nBranch head SHA: %s\nCandidate/actual merge SHA: %s\n" \
-            "$SHORT_SHA_BRANCH_BASE" "$SHORT_SHA_BRANCH_HEAD" "$SHORT_SHA_MERGE"
-
-          echo "short_sha_branch_base=$SHORT_SHA_BRANCH_BASE" >> $GITHUB_OUTPUT
-          echo "short_sha_branch_head=$SHORT_SHA_BRANCH_HEAD" >> $GITHUB_OUTPUT
-          echo "short_sha_merge=$SHORT_SHA_MERGE" >> $GITHUB_OUTPUT
-
-      - name: Configure AWS credentials
-        id: configure-aws
-        uses: aws-actions/configure-aws-credentials@v6.0.0
-        with:
-          aws-access-key-id:
-            ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key:
-            ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region:
-            ${{ vars.AWS_REGION }}
-
-      - name: Fetch base manifest
-        id: fetch-manifest
-        run: |
-          MANIFEST_ID="${{ steps.short-shas.outputs.short_sha_branch_base }}"
-
-          echo "Fetching manifest with id $MANIFEST_ID from S3..."
-          aws s3 cp \
-            --region "${{ vars.AWS_REGION }}" \
-            "s3://${{ vars.MANIFEST_BUCKET }}/${MANIFEST_ID}.json" \
-            manifest.json
-          echo "Manifest fetched successfully."
-
-      - name: Upload manifest artefact
-        uses: actions/upload-artifact@v4
-        with:
-          name: base-manifest-${{ github.run_id }}
-          path: manifest.json
-          if-no-files-found: error
-          retention-days: 1
- 
   python-test-and-deploy:
     runs-on: ubuntu-latest
     environment: stage
@@ -365,13 +395,13 @@ jobs:
             -out=tfplan \
             -var-file="envs/stage/terraform.tfvars" \
             -var="BUDIBASE_TASK_COUNT=1"
-          exit_code=$?
+          EXIT_CODE="$?"
           set -e
 
-          if [ $exit_code -eq 2 ]; then
+          if [ $EXIT_CODE -eq 2 ]; then
             echo "Changes detected in Terraform configuration."
             echo "runapply=true" >> $GITHUB_OUTPUT
-          elif [ $exit_code -eq 1 ]; then
+          elif [ $EXIT_CODE -eq 1 ]; then
             echo "Error during Terraform plan."
             exit 1
           else
